# Generated by Django 5.1.6 on 2025-02-13 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_alter_department_slug'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gender',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.gender'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='departments.department'),
        ),
    ]
