# Generated by Django 5.1.6 on 2025-02-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_remove_subject_teacher'),
        ('teachers', '0003_teacher_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(related_name='teachers', to='subjects.subject'),
        ),
    ]
