# Generated by Django 5.1.6 on 2025-02-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_teacher_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
