# Generated by Django 5.1.6 on 2025-02-13 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_alter_teacher_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='position',
        ),
    ]
