# Generated by Django 5.1.6 on 2025-02-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_alter_teacher_employment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='employment_type',
            field=models.CharField(max_length=100),
        ),
    ]
