# Generated by Django 5.1.6 on 2025-02-13 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_alter_teacher_employment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='employment_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='teachers.employmenttype'),
        ),
    ]
