# Generated by Django 5.1.6 on 2025-02-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('academic_year', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('max_students', models.PositiveIntegerField()),
                ('grade_level', models.CharField(max_length=2)),
                ('teacher', models.ManyToManyField(related_name='groups', to='teachers.teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
