# Generated by Django 5.1.6 on 2025-02-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('subjects', '0003_remove_subject_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='subjects',
            field=models.ManyToManyField(related_name='groups', to='subjects.subject'),
        ),
    ]
