# Generated by Django 5.1.6 on 2025-02-14 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
