# Generated by Django 5.1.6 on 2025-02-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_alter_group_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='grade_level',
            field=models.PositiveIntegerField(max_length=2),
        ),
    ]
