# Generated by Django 5.1.6 on 2025-02-15 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_alter_group_grade_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='schedule',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='groups.schedule'),
        ),
    ]
