# Generated by Django 5.1.6 on 2025-02-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_group_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='grade_level',
            field=models.PositiveIntegerField(),
        ),
    ]
