# Generated by Django 5.1.6 on 2025-02-09 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0002_initial'),
        ('groups', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('credit_hours', models.PositiveIntegerField()),
                ('department', models.ManyToManyField(related_name='subjects', to='departments.department')),
                ('grade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='students.grade')),
                ('group', models.ManyToManyField(related_name='subjects', to='groups.group')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='subjects', to='subjects.subject')),
                ('student', models.ManyToManyField(related_name='subjects', to='students.student')),
                ('teacher', models.ManyToManyField(related_name='subjects', to='teachers.teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
