# Generated by Django 5.1.6 on 2025-02-14 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_remove_subject_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='group',
        ),
    ]
