# Generated by Django 5.1.6 on 2025-02-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_remove_subject_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, null=True, related_name='subjects', to='subjects.subject'),
        ),
    ]
